/**
 * W6 · Starter tests — every visual starter compiles to Handlebars and renders
 * through the REAL templateMerge against sample data, structurally matching its
 * seeded counterpart (title, both parties, terms, the line-items loop, totals,
 * notes, footer). Run from apps/portal:
 *   ../../tests/rls-and-perf/node_modules/.bin/tsx src/features/documents/compiler/starters/__tests__/starters.test.ts
 */
import { compileTemplate } from "../../index";
import { STARTERS } from "../index";
import { mergeTemplate } from "../../../../orders/services/documents/templateMerge";
import { DOC_TITLES } from "../../../../orders/services/documents/types";
import type { DocType } from "../../../../orders/services/dealModel";

let pass = 0;
let fail = 0;
const ok = (n: string, c: boolean) => {
  if (c) pass++;
  else {
    fail++;
    console.log("  ✗ FAIL: " + n);
  }
};

function sample(docType: DocType) {
  return {
    docType,
    docTitle: DOC_TITLES[docType],
    docNumber: "No. 1",
    docDate: "2026-07-02T00:00:00Z",
    dealCode: "TIMSOM001",
    currency: "EUR",
    seller: { name: "Timber World SIA", address: "Brivibas 1, Riga", regNo: "40000", vatNo: "LV40000", email: "s@tw.lv", phone: "+371", bankName: "Swedbank", bankAccount: "LV00", bankSwift: "HABA" },
    buyer: { name: "DDC Ltd", address: "London", regNo: "GB1", vatNo: "GB1", email: "b@ddc.uk", phone: "+44" },
    externalRefs: [],
    incoterms: "FCA Riga", paymentTerms: "30% advance", deliveryTerms: "By truck", deliveryDeadline: "2026-08-15", advancePct: 30,
    lineItems: [
      { lineNo: 1, description: "Oak board", dimensions: "27x150x2000", pieces: "120", volumeM3: 0.972, unit: "m3", unitPriceCents: 68000, lineTotalCents: 66096 },
      { lineNo: 2, description: "Pine plank", dimensions: "50x200x3000", pieces: "40", volumeM3: 1.2, unit: "m3", unitPriceCents: 32000, lineTotalCents: 38400 },
    ],
    totals: { totalVolumeM3: 2.172, subtotalCents: 104496, vatRate: 21, vatReference: null, vatCents: 21944, totalCents: 126440, amountInWords: "one hundred twenty-six euros" },
    notes: "Goods remain property of the seller until paid.",
  };
}

const PRICE_TYPES = new Set(["sales_spec", "purchase_spec", "contract", "proforma_invoice", "invoice"]);
const docTypes = Object.keys(STARTERS) as DocType[];

ok("all 7 doc types have a starter", docTypes.length === 7);

for (const dt of docTypes) {
  const env = STARTERS[dt]();
  let compiled = "";
  let merged = "";
  let threw = false;
  try {
    compiled = compileTemplate(env.doc, { pageSettings: env.pageSettings, docType: dt });
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    merged = mergeTemplate(compiled, sample(dt) as any);
  } catch {
    threw = true;
  }

  console.log(`── ${dt} ──`);
  ok(`${dt}: compiles + merges without throwing (valid Handlebars)`, !threw);
  if (threw) continue;
  ok(`${dt}: title rendered`, merged.includes(DOC_TITLES[dt]));
  ok(`${dt}: seller name rendered`, merged.includes("Timber World SIA"));
  ok(`${dt}: buyer/counterparty name rendered`, merged.includes("DDC Ltd"));
  ok(`${dt}: line-items loop rendered (both rows)`, merged.includes("Oak board") && merged.includes("Pine plank"));
  ok(`${dt}: compiled uses <tbody>{{#each lineItems}}…{{/each}}</tbody>`, /<tbody>\{\{#each lineItems\}\}.*\{\{\/each\}\}<\/tbody>/.test(compiled));
  ok(`${dt}: volume rendered (fmtM3)`, merged.includes("0,972"));
  ok(`${dt}: footer present`, merged.includes("Generated by Timber World"));
  ok(`${dt}: NO unresolved {{ left`, !merged.includes("{{"));

  if (PRICE_TYPES.has(dt)) {
    ok(`${dt}: has priced total (moneyCur → '1 264,40 EUR')`, merged.includes("1 264,40 EUR"));
    ok(`${dt}: line total money rendered ('660,96')`, merged.includes("660,96"));
  } else {
    ok(`${dt}: NO price columns (no unit-price/line-total cells)`, !compiled.includes("{{money unitPriceCents}}") && !compiled.includes("{{money lineTotalCents}}"));
    ok(`${dt}: still shows total volume`, merged.includes("Total volume:"));
  }
}

console.log(`\nW6 starters: ${pass} passed, ${fail} failed`);
if (fail > 0) process.exit(1);
