services:
  mailpit:
    image: axllent/mailpit:v1.30.6
    ports:
      - "127.0.0.1:8027:8025"
      - "127.0.0.1:1027:1025"
    environment:
      MP_MAX_MESSAGES: 500
      MP_MAX_MESSAGE_SIZE: 10MB
