/**
 * Visual starter documents (W6) — one TemplateEnvelope per doc type, authored as
 * TipTap JSON so opening "New from starter" gives a complete, editable A4 page
 * (never a blank canvas) that structurally mirrors the seeded default templates
 * (party details, terms, the repeating line-items table, totals, notes, footer).
 *
 * PURE data (no react/@tiptap). The compiler turns these into Handlebars-HTML;
 * the same {{ }} tokens/helpers as the seeded templates are used, so they render
 * through the frozen pipeline identically. Prices/columns vary per doc type.
 */
import { MERGE_FIELD_LABELS } from "../registry";
import type { TemplateEnvelope, TipTapDoc, TipTapNode } from "../types";
import type { DocType } from "../../../orders/services/dealModel";

// ── node builders ───────────────────────────────────────────────────────────
const text = (t: string, marks?: string[]): TipTapNode => ({
  type: "text",
  text: t,
  ...(marks ? { marks: marks.map((m) => ({ type: m })) } : {}),
});
/** A merge-field pill (friendly label pulled from the shared registry). */
const pill = (token: string): TipTapNode => ({
  type: "mergeField",
  attrs: { token, label: MERGE_FIELD_LABELS[token] ?? token },
});
const p = (...content: TipTapNode[]): TipTapNode =>
  content.length ? { type: "paragraph", content } : { type: "paragraph" };
const pAlign = (align: string, ...content: TipTapNode[]): TipTapNode => ({
  type: "paragraph",
  attrs: { textAlign: align },
  content,
});
/** Paragraph hidden entirely when its first field has no value ({{#if}}). */
const pIf = (...content: TipTapNode[]): TipTapNode => ({
  type: "paragraph",
  attrs: { hideWhenEmpty: true },
  content,
});
const h = (level: number, ...content: TipTapNode[]): TipTapNode => ({
  type: "heading",
  attrs: { level },
  content,
});
const hAlign = (level: number, align: string, ...content: TipTapNode[]): TipTapNode => ({
  type: "heading",
  attrs: { level, textAlign: align },
  content,
});
const hr = (): TipTapNode => ({ type: "horizontalRule" });
const lineItems = (columns: string[]): TipTapNode => ({ type: "lineItemsTable", attrs: { columns } });
const doc = (...content: TipTapNode[]): TipTapDoc => ({ type: "doc", content });

// ── column sets ───────────────────────────────────────────────────────────
const FULL = ["lineNo", "description", "dimensions", "pieces", "volumeM3", "unitPriceCents", "lineTotalCents"];
const NO_PRICES = ["lineNo", "description", "dimensions", "pieces", "volumeM3"];
const CMR_COLS = ["lineNo", "description", "pieces", "volumeM3"];

// ── shared blocks ───────────────────────────────────────────────────────────
/** Stacked party block: heading + name + optional address / ids / contact / bank. */
function party(label: string, prefix: "seller" | "buyer", opts: { bank?: boolean } = {}): TipTapNode[] {
  const f = (k: string) => `${prefix}.${k}`;
  const rows: TipTapNode[] = [
    h(3, text(label)),
    p(pill(f("name"))),
    pIf(pill(f("address"))),
    pIf(text("Reg. No: "), pill(f("regNo"))),
    pIf(text("VAT: "), pill(f("vatNo"))),
    pIf(pill(f("email"))),
    pIf(pill(f("phone"))),
  ];
  if (opts.bank) {
    rows.push(pIf(text("Bank: "), pill(f("bankName"))));
    rows.push(pIf(text("Account: "), pill(f("bankAccount"))));
    rows.push(pIf(text("SWIFT: "), pill(f("bankSwift"))));
  }
  return rows;
}

const termsBlock = (): TipTapNode[] => [
  pIf(text("Incoterms: "), pill("incoterms")),
  pIf(text("Payment: "), pill("paymentTerms")),
  pIf(text("Delivery: "), pill("deliveryTerms")),
  pIf(text("Deadline: "), pill("deliveryDeadline")),
  pIf(text("Advance: "), pill("pct advancePct")),
];

const totalsBlock = (): TipTapNode[] => [
  pAlign("right", text("Total volume: "), pill("fmtM3 totals.totalVolumeM3"), text(" m³")),
  pAlign("right", text("Subtotal: "), pill("money totals.subtotalCents"), text(" "), pill("currency")),
  pAlign("right", text("VAT ("), pill("pct totals.vatRate"), text("): "), pill("money totals.vatCents"), text(" "), pill("currency")),
  pAlign("right", text("Total: ", ["bold"]), pill("moneyCur totals.totalCents")),
  pIf(text("In words: ", ["italic"]), pill("totals.amountInWords")),
];

const footerBlock = (): TipTapNode[] => [
  hr(),
  pAlign("center", text("Generated by Timber World · "), pill("docNumber"), text(" · Deal "), pill("dealCode")),
];

const header = (): TipTapNode[] => [
  hAlign(1, "center", pill("docTitle")),
  pAlign("center", text("No. "), pill("docNumber"), text(" · Deal "), pill("dealCode"), text(" · "), pill("fmtDate docDate")),
  hr(),
];

// ── spec/invoice-shaped starter (parties + terms + line items + optional totals) ──
function specStarter(opts: {
  sellerLabel: string;
  buyerLabel: string;
  sellerBank: boolean;
  buyerBank: boolean;
  columns: string[];
  totals: boolean;
  marginMm?: number;
}): TemplateEnvelope {
  return {
    pageSettings: { marginMm: opts.marginMm ?? 12 },
    doc: doc(
      ...header(),
      ...party(opts.sellerLabel, "seller", { bank: opts.sellerBank }),
      ...party(opts.buyerLabel, "buyer", { bank: opts.buyerBank }),
      ...termsBlock(),
      h(3, text("Goods")),
      lineItems(opts.columns),
      ...(opts.totals ? totalsBlock() : [pAlign("right", text("Total volume: "), pill("fmtM3 totals.totalVolumeM3"), text(" m³"))]),
      pIf(text("Notes: ", ["bold"]), pill("notes")),
      ...footerBlock()
    ),
  };
}

// ── sales contract starter (clauses + annex + signatures) ────────────────────
function contractStarter(): TemplateEnvelope {
  return {
    pageSettings: { marginMm: 14 },
    doc: doc(
      hAlign(1, "center", pill("docTitle")),
      pAlign("center", text("No. "), pill("docNumber"), text(" · Deal "), pill("dealCode"), text(" · "), pill("fmtDate docDate")),
      hr(),
      ...party("Seller", "seller", { bank: true }),
      ...party("Buyer", "buyer"),
      h(3, text("1. Subject")),
      p(text("The Seller sells and the Buyer buys the goods specified in the annex below, on the terms set out in this contract.")),
      h(3, text("2. Price & payment")),
      pIf(text("Payment terms: "), pill("paymentTerms")),
      pIf(text("Incoterms: "), pill("incoterms")),
      p(text("Total contract value: "), pill("moneyCur totals.totalCents"), text(" (VAT "), pill("pct totals.vatRate"), text(").")),
      h(3, text("3. Delivery")),
      pIf(text("Delivery terms: "), pill("deliveryTerms")),
      pIf(text("Delivery deadline: "), pill("deliveryDeadline")),
      h(3, text("4. Goods (annex)")),
      lineItems(FULL),
      ...totalsBlock(),
      pIf(text("Notes: ", ["bold"]), pill("notes")),
      h(3, text("Signatures")),
      p(text("Seller: ______________________          Buyer: ______________________")),
      ...footerBlock()
    ),
  };
}

// ── the 7 starters, keyed by doc type ────────────────────────────────────────
export const STARTERS: Record<DocType, () => TemplateEnvelope> = {
  sales_spec: () =>
    specStarter({ sellerLabel: "Seller", buyerLabel: "Buyer", sellerBank: true, buyerBank: false, columns: FULL, totals: true }),
  purchase_spec: () =>
    specStarter({ sellerLabel: "Buyer", buyerLabel: "Producer / Supplier", sellerBank: false, buyerBank: true, columns: FULL, totals: true }),
  contract: () => contractStarter(),
  proforma_invoice: () =>
    specStarter({ sellerLabel: "Seller", buyerLabel: "Buyer", sellerBank: true, buyerBank: false, columns: FULL, totals: true }),
  invoice: () =>
    specStarter({ sellerLabel: "Seller", buyerLabel: "Buyer", sellerBank: true, buyerBank: false, columns: FULL, totals: true }),
  packing_list: () =>
    specStarter({ sellerLabel: "Consignor", buyerLabel: "Consignee", sellerBank: false, buyerBank: false, columns: NO_PRICES, totals: false }),
  cmr: () =>
    specStarter({ sellerLabel: "Sender", buyerLabel: "Consignee", sellerBank: false, buyerBank: false, columns: CMR_COLS, totals: false }),
};

/** Build a fresh starter envelope for a doc type (deep-copied via the builder fns). */
export function starterFor(docType: DocType): TemplateEnvelope {
  return (STARTERS[docType] ?? STARTERS.sales_spec)();
}
