"use client";

/**
 * Page settings for a visual template — logo/letterhead upload (public bucket),
 * A4 margin, and an optional running footer. Compiles into the document shell
 * (@page margin + logo header + footer div).
 */
import { useRef, useState } from "react";
import { toast } from "sonner";
import { Image as ImageIcon, Loader2, Trash2, Upload } from "lucide-react";
import { Button, Input } from "@timber/ui";
import { removeTemplateLogo, uploadTemplateLogo } from "../actions";
import type { PageSettings } from "../types";

export function PageSettingsPanel({
  templateId,
  logoPath,
  pageSettings,
  onChange,
}: {
  templateId?: string;
  logoPath?: string | null;
  pageSettings: PageSettings | null;
  onChange: (ps: PageSettings) => void;
}) {
  const ps: PageSettings = pageSettings ?? {};
  const fileRef = useRef<HTMLInputElement>(null);
  const [uploading, setUploading] = useState(false);

  const patch = (p: Partial<PageSettings>) => onChange({ ...ps, ...p });

  const onFile = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    e.target.value = "";
    if (!file) return;
    setUploading(true);
    const fd = new FormData();
    fd.append("file", file);
    fd.append("templateId", templateId ?? "tmp");
    const res = await uploadTemplateLogo(fd);
    setUploading(false);
    if (!res.success) {
      toast.error(res.error);
      return;
    }
    patch({ logoUrl: res.data.url });
    toast.success("Logo uploaded");
  };

  const removeLogo = async () => {
    patch({ logoUrl: null });
    // Best-effort delete of the stored object (only if we know its path).
    if (logoPath) await removeTemplateLogo(logoPath);
  };

  return (
    <div className="flex flex-wrap items-end gap-4 rounded-md border bg-muted/20 p-3">
      <div className="space-y-1">
        <label className="text-xs text-muted-foreground">Logo / letterhead</label>
        <div className="flex items-center gap-2">
          {ps.logoUrl ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img src={ps.logoUrl} alt="Logo" className="h-8 max-w-[120px] rounded border object-contain" />
          ) : (
            <div className="flex h-8 w-8 items-center justify-center rounded border text-muted-foreground">
              <ImageIcon className="h-4 w-4" />
            </div>
          )}
          <Button variant="outline" size="sm" onClick={() => fileRef.current?.click()} disabled={uploading}>
            {uploading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />}
            {ps.logoUrl ? "Replace" : "Upload"}
          </Button>
          {ps.logoUrl && (
            <Button variant="ghost" size="sm" onClick={removeLogo} title="Remove logo">
              <Trash2 className="h-4 w-4" />
            </Button>
          )}
          <input
            ref={fileRef}
            type="file"
            accept="image/png,image/jpeg,image/webp"
            className="hidden"
            onChange={onFile}
          />
        </div>
      </div>

      <div className="space-y-1">
        <label htmlFor="ps-margin" className="text-xs text-muted-foreground">
          Page margin (mm)
        </label>
        <Input
          id="ps-margin"
          type="number"
          min={0}
          max={40}
          value={ps.marginMm ?? 12}
          onChange={(e) => patch({ marginMm: e.target.value === "" ? undefined : Number(e.target.value) })}
          className="w-24"
        />
      </div>

      <div className="min-w-[220px] flex-1 space-y-1">
        <label htmlFor="ps-footer" className="text-xs text-muted-foreground">
          Running footer (optional)
        </label>
        <Input
          id="ps-footer"
          value={ps.footerText ?? ""}
          onChange={(e) => patch({ footerText: e.target.value || null })}
          placeholder="e.g. Generated by Timber World"
        />
      </div>
    </div>
  );
}
