"use client";

import { useState } from "react";
import { ArrowDown, ArrowUp, Loader2, Plus } from "lucide-react";
import { Button, Checkbox, Input, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@timber/ui";
import { toast } from "sonner";
import { createProjectStage, reorderProjectStages, updateProjectStageDefinition } from "../actions";
import type { StageOption } from "../stages";

type Draft = Pick<StageOption,"key"|"label"|"color"|"isActive"|"availableToBuyer"|"availableToTrader"|"availableToSupplier">;
const blank: Draft = { key:"", label:"", color:"#64748B", isActive:true, availableToBuyer:true, availableToTrader:true, availableToSupplier:true };

export function ProjectStagesSettings({ initialStages }: { initialStages: StageOption[] }) {
  const [stages,setStages]=useState(initialStages); const [draft,setDraft]=useState(blank); const [busy,setBusy]=useState<string|null>(null);
  async function save(stage: StageOption){setBusy(stage.key);try{const result=await updateProjectStageDefinition(stage);if(!result.success){toast.error(result.error);return}setStages((rows)=>rows.map((row)=>row.key===stage.key?result.data:row));toast.success("Stage saved")}catch{toast.error("Could not save stage")}finally{setBusy(null)}}
  async function create(){setBusy("new");try{const result=await createProjectStage(draft);if(!result.success){toast.error(result.error);return}setStages((rows)=>[...rows,result.data]);setDraft(blank);toast.success("Stage created")}catch{toast.error("Could not create stage")}finally{setBusy(null)}}
  async function move(index:number,delta:number){const target=index+delta;if(target<0||target>=stages.length)return;const previous=stages;const next=[...stages];[next[index],next[target]]=[next[target]!,next[index]!];setStages(next);setBusy("order");try{const result=await reorderProjectStages({items:next.map((row,i)=>({key:row.key,sortOrder:(i+1)*10}))});if(!result.success){setStages(previous);toast.error(result.error);return}toast.success("Stage order updated")}catch{setStages(previous);toast.error("Could not reorder stages")}finally{setBusy(null)}}
  return <div className="space-y-6"><div className="rounded-lg border bg-card p-4"><h2 className="font-semibold">Add stage</h2><p className="mb-4 text-sm text-muted-foreground">Keys are permanent after creation. Labels and presentation remain editable.</p><div className="grid gap-3 md:grid-cols-3"><Input aria-label="Stage key" placeholder="stage_key" value={draft.key} onChange={(e)=>setDraft({...draft,key:e.target.value})}/><Input aria-label="Stage label" placeholder="Stage label" value={draft.label} onChange={(e)=>setDraft({...draft,label:e.target.value})}/><label className="flex h-9 items-center gap-2"><input aria-label="Stage colour" type="color" value={draft.color} onChange={(e)=>setDraft({...draft,color:e.target.value})}/><span className="text-sm">{draft.color}</span></label></div><RoleChecks value={draft} onChange={setDraft}/><Button className="mt-4" size="sm" disabled={busy!==null} onClick={()=>void create()}>{busy==="new"?<Loader2 className="h-4 w-4 animate-spin"/>:<Plus className="h-4 w-4"/>} Add stage</Button></div><Table dense><TableHeader><TableRow><TableHead>Order</TableHead><TableHead>Key</TableHead><TableHead>Label</TableHead><TableHead>Colour</TableHead><TableHead>Active</TableHead><TableHead>Buyer</TableHead><TableHead>Trader</TableHead><TableHead>Supplier</TableHead><TableHead /></TableRow></TableHeader><TableBody>{stages.map((stage,index)=><StageRow key={stage.key} stage={stage} index={index} count={stages.length} busy={busy!==null} onChange={(next)=>setStages((rows)=>rows.map((row)=>row.key===next.key?next:row))} onSave={save} onMove={move}/>)}</TableBody></Table></div>;
}
function StageRow({stage,index,count,busy,onChange,onSave,onMove}:{stage:StageOption;index:number;count:number;busy:boolean;onChange:(stage:StageOption)=>void;onSave:(stage:StageOption)=>Promise<void>;onMove:(index:number,delta:number)=>Promise<void>}){return <TableRow><TableCell><div className="flex"><Button size="icon" variant="ghost" disabled={busy||index===0} aria-label={`Move ${stage.label} up`} onClick={()=>void onMove(index,-1)}><ArrowUp className="h-4 w-4"/></Button><Button size="icon" variant="ghost" disabled={busy||index===count-1} aria-label={`Move ${stage.label} down`} onClick={()=>void onMove(index,1)}><ArrowDown className="h-4 w-4"/></Button></div></TableCell><TableCell><code>{stage.key}</code></TableCell><TableCell><Input aria-label={`${stage.key} label`} value={stage.label} onChange={(e)=>onChange({...stage,label:e.target.value})}/></TableCell><TableCell><input aria-label={`${stage.key} colour`} type="color" value={stage.color} onChange={(e)=>onChange({...stage,color:e.target.value})}/></TableCell><CheckCell checked={stage.isActive} label={`${stage.key} active`} onChange={(checked)=>onChange({...stage,isActive:checked})}/><CheckCell checked={stage.availableToBuyer} label={`${stage.key} buyer`} onChange={(checked)=>onChange({...stage,availableToBuyer:checked})}/><CheckCell checked={stage.availableToTrader} label={`${stage.key} trader`} onChange={(checked)=>onChange({...stage,availableToTrader:checked})}/><CheckCell checked={stage.availableToSupplier} label={`${stage.key} supplier`} onChange={(checked)=>onChange({...stage,availableToSupplier:checked})}/><TableCell><Button size="sm" variant="outline" disabled={busy} onClick={()=>void onSave(stage)}>Save</Button></TableCell></TableRow>}
function CheckCell({checked,label,onChange}:{checked:boolean;label:string;onChange:(checked:boolean)=>void}){return <TableCell><Checkbox aria-label={label} checked={checked} onCheckedChange={(value)=>onChange(value===true)}/></TableCell>}
function RoleChecks({value,onChange}:{value:Draft;onChange:(draft:Draft)=>void}){return <div className="mt-3 flex flex-wrap gap-5"><label className="flex items-center gap-2 text-sm"><Checkbox checked={value.isActive} onCheckedChange={(v)=>onChange({...value,isActive:v===true})}/> Active</label>{([['availableToBuyer','Buyer'],['availableToTrader','Trader'],['availableToSupplier','Supplier']] as const).map(([key,label])=><label key={key} className="flex items-center gap-2 text-sm"><Checkbox checked={value[key]} onCheckedChange={(v)=>onChange({...value,[key]:v===true})}/> {label}</label>)}</div>}
