"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createAdminClient as createTypedAdminClient } from "@/lib/supabase/admin";
import type { DbClient } from "../../orders/services/dealModel";
import type { ActionResult } from "../../orders/types";
import { resolveProjectsActor,resolveProjectsViewer } from "../access";

const uuid=z.string().uuid();
const createAdminClient=()=>createTypedAdminClient() as unknown as DbClient;
const contribution=z.object({sourceOrderId:uuid,originLineItemId:uuid,selectedQuantity:z.number().finite().positive(),sourceVersion:z.number().int().nonnegative(),sourceUpdatedAt:z.string().datetime()});
const saveSchema=z.object({projectId:uuid,scope:z.enum(["full","partial"]),sources:z.array(contribution).min(1).max(500),adjustmentCents:z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER),marginMode:z.enum(["amount","percentage"]),marginValue:z.number().finite().nonnegative()});
const decisionSchema=z.object({projectId:uuid,decision:z.enum(["accepted","rejected"]),notes:z.string().max(4000).optional()});
export type CommercialSourceLine={originLineItemId:string;availableQuantity:number;sourceAmountCents:number};
export type CommercialSource={sourceOrderId:string;sourceCandidateId:string|null;reference:string;currency:string;sourceVersion:number;sourceUpdatedAt:string;sellerName:string;wholePackage?:boolean;lines:CommercialSourceLine[]};
export type CommercialRollupState={canBuild:boolean;canDecide:boolean;state:"draft"|"published"|"accepted"|"rejected"|"stale";scope:"full"|"partial"|null;offerNotes?:string|null;buyerNotes?:string|null;publishedAt?:string|null;decidedAt?:string|null;marginMode?:"amount"|"percentage"|null;purchaseCostCents?:number|null;adjustmentCents?:number|null;marginAmountCents?:number|null;marginPercent?:number|null;salesAmountCents:number|null;lines:Array<{originLineItemId:string;offeredQuantity:number;offeredValueCents:number;purchaseCostCents?:number;adjustmentCents?:number;marginCents?:number}>;sources?:CommercialSource[];savedSelections?:Array<{sourceOrderId:string;originLineItemId:string;selectedQuantity:number}>;requiredLines?:Array<{originLineItemId:string;label:string;requiredQuantity:number}>};
async function visibleOrder(projectId:string){const actor=await resolveProjectsActor();if(!actor.ok)return null;const{data}=await actor.db.from("orders").select("id,seller_organisation_id,buyer_organisation_id,commercial_rollup_state,commercial_offer_scope,commercial_margin_mode,commercial_purchase_cost_cents,commercial_adjustment_cents,margin_amount_cents,margin_percent,resale_value_cents,commercial_published_at,commercial_decided_at,commercial_offer_notes,commercial_buyer_notes").eq("id",projectId).is("deleted_at",null).maybeSingle();return data?{actor,order:data}:null}
export async function getProjectCommercialRollup(projectId:string):Promise<ActionResult<CommercialRollupState>>{
  if(!uuid.safeParse(projectId).success)return{success:false,error:"Project unavailable",code:"NOT_FOUND"};const ctx=await visibleOrder(projectId);if(!ctx)return{success:false,error:"Project unavailable",code:"NOT_FOUND"};
  const viewer=await resolveProjectsViewer(ctx.actor);const isTrader=viewer.canCreateProject&&viewer.createRoles.includes("trader");const admin=createAdminClient();const{data:awardedRfq,error:awardedError}=await admin.from("project_rfqs").select("project_rfq_candidates!project_rfqs_awarded_candidate_fk(organization_id)").eq("order_id",projectId).eq("status","awarded").order("created_at",{ascending:false}).limit(1).maybeSingle();if(awardedError)return{success:false,error:"Could not load commercial offer",code:"FETCH_FAILED"};const awardedCandidate=awardedRfq?.project_rfq_candidates as {organization_id:string}|null|undefined;const isAwardedSupplier=Boolean(ctx.actor.orgId&&awardedCandidate?.organization_id===ctx.actor.orgId);const canBuild=ctx.actor.isPlatformAdmin||Boolean(ctx.actor.orgId&&ctx.order.seller_organisation_id===ctx.actor.orgId&&isTrader&&!isAwardedSupplier);const canViewPrivate=canBuild;
  const{count:sourceCount,error:sourceCountError}=await admin.from("project_leg_commercial_sources").select("id",{count:"exact",head:true}).eq("target_order_id",projectId);if(sourceCountError)return{success:false,error:"Could not load commercial offer",code:"FETCH_FAILED"};const buyerVisible=["published","accepted","rejected"].includes(String(ctx.order.commercial_rollup_state));const canDecide=Boolean(ctx.actor.orgId===ctx.order.buyer_organisation_id&&ctx.order.commercial_rollup_state==="published"&&(sourceCount??0)>0);const canViewOffer=ctx.actor.isPlatformAdmin||Boolean(ctx.actor.orgId===ctx.order.buyer_organisation_id&&buyerVisible&&(sourceCount??0)>0)||canBuild;
  const{data:lines,error:linesError}=await admin.from("project_leg_commercial_lines").select("origin_line_item_id,offered_quantity,purchase_cost_cents,adjustment_cents,margin_cents,offered_value_cents").eq("target_order_id",projectId).order("origin_line_item_id");if(linesError)return{success:false,error:"Could not load commercial offer",code:"FETCH_FAILED"};
  const safeLines=canViewOffer?(lines??[]).map((line:{origin_line_item_id:string;offered_quantity:number|string;offered_value_cents:number|string;purchase_cost_cents:number|string;adjustment_cents:number|string;margin_cents:number|string})=>({originLineItemId:line.origin_line_item_id,offeredQuantity:Number(line.offered_quantity),offeredValueCents:Number(line.offered_value_cents),...(canViewPrivate?{purchaseCostCents:Number(line.purchase_cost_cents),adjustmentCents:Number(line.adjustment_cents),marginCents:Number(line.margin_cents)}:{})})):[];
  let sources:CommercialSource[]|undefined;let savedSelections:CommercialRollupState["savedSelections"];let requiredLines:CommercialRollupState["requiredLines"];
  if(canBuild){const{data,error}=await ctx.actor.db.rpc("get_project_commercial_sources",{p_target_order_id:projectId});if(error)return{success:false,error:"Could not load eligible commercial sources",code:"FETCH_FAILED"};sources=(Array.isArray(data)?data:[]) as CommercialSource[];const[{data:saved,error:savedError},{data:requirements,error:requirementsError}]=await Promise.all([admin.from("project_leg_commercial_sources").select("source_order_id,origin_line_item_id,selected_quantity").eq("target_order_id",projectId),admin.from("order_line_items").select("id,origin_line_item_id,product_name,work_package_quantity,volume_m3,pieces").eq("order_id",projectId).eq("side","sell")]);if(savedError||requirementsError)return{success:false,error:"Could not load commercial offer details",code:"FETCH_FAILED"};savedSelections=(saved??[]).map((row:{source_order_id:string;origin_line_item_id:string;selected_quantity:number|string})=>({sourceOrderId:row.source_order_id,originLineItemId:row.origin_line_item_id,selectedQuantity:Number(row.selected_quantity)}));const grouped=new Map<string,{originLineItemId:string;label:string;requiredQuantity:number}>();for(const line of (requirements??[]) as Array<{id:string;origin_line_item_id:string|null;product_name:string|null;work_package_quantity:number|string|null;volume_m3:number|string|null;pieces:number|string|null}>){const id=line.origin_line_item_id??line.id;const quantity=Number(line.work_package_quantity??line.volume_m3??line.pieces??0);const current=grouped.get(id);grouped.set(id,{originLineItemId:id,label:current?.label??line.product_name??"Specification line",requiredQuantity:(current?.requiredQuantity??0)+quantity})}requiredLines=[...grouped.values()].filter((line)=>line.requiredQuantity>0)}
  return{success:true,data:{canBuild,canDecide,state:canViewOffer?ctx.order.commercial_rollup_state as CommercialRollupState["state"]:"draft",scope:canViewOffer?ctx.order.commercial_offer_scope as CommercialRollupState["scope"]:null,offerNotes:canViewOffer?ctx.order.commercial_offer_notes as string|null:null,buyerNotes:canViewOffer?ctx.order.commercial_buyer_notes as string|null:null,publishedAt:canViewOffer?ctx.order.commercial_published_at as string|null:null,decidedAt:canViewOffer?ctx.order.commercial_decided_at as string|null:null,salesAmountCents:canViewOffer&&ctx.order.resale_value_cents!=null?Number(ctx.order.resale_value_cents):null,lines:safeLines,...(canBuild?{marginMode:ctx.order.commercial_margin_mode as CommercialRollupState["marginMode"],purchaseCostCents:ctx.order.commercial_purchase_cost_cents==null?null:Number(ctx.order.commercial_purchase_cost_cents),adjustmentCents:ctx.order.commercial_adjustment_cents==null?null:Number(ctx.order.commercial_adjustment_cents),marginAmountCents:ctx.order.margin_amount_cents==null?null:Number(ctx.order.margin_amount_cents),marginPercent:ctx.order.margin_percent==null?null:Number(ctx.order.margin_percent),sources,savedSelections,requiredLines}:{})}};
}
function mapRollupError(message:string):string{if(message.includes("INCOMPLETE_COVERAGE"))return"Full offer does not cover every specification line";if(message.includes("OVER_COVERAGE"))return"Selected quantities exceed the specification";if(message.includes("STALE_OR_INVALID_SOURCE"))return"A source quotation changed; reload and review it";if(message.includes("CIRCULAR_SOURCE"))return"This selection would create a circular commercial dependency";if(message.includes("FORBIDDEN"))return"You are not allowed to save this buyer offer";return"Could not save the buyer offer"}
export async function saveProjectCommercialRollup(raw:unknown):Promise<ActionResult<CommercialRollupState>>{const parsed=saveSchema.safeParse(raw);if(!parsed.success)return{success:false,error:parsed.error.issues[0]?.message??"Invalid selling price",code:"VALIDATION_ERROR"};if(parsed.data.marginMode==="percentage"&&parsed.data.marginValue>=100)return{success:false,error:"Margin percentage must be below 100",code:"VALIDATION_ERROR"};const actor=await resolveProjectsActor();if(!actor.ok)return{success:false,error:"Not allowed",code:"FORBIDDEN"};const{error}=await actor.db.rpc("save_project_commercial_rollup",{p_target_order_id:parsed.data.projectId,p_scope:parsed.data.scope,p_sources:parsed.data.sources,p_adjustment_cents:parsed.data.adjustmentCents,p_margin_mode:parsed.data.marginMode,p_margin_value:parsed.data.marginValue});if(error)return{success:false,error:mapRollupError(error.message),code:error.message.includes("FORBIDDEN")?"FORBIDDEN":"VALIDATION_ERROR"};revalidatePath(`/projects/${parsed.data.projectId}`);revalidatePath("/projects");return getProjectCommercialRollup(parsed.data.projectId)}
export async function publishProjectCommercialOffer(projectId:string,offerNotes?:string):Promise<ActionResult<CommercialRollupState>>{if(!uuid.safeParse(projectId).success||typeof offerNotes==="string"&&offerNotes.length>4000)return{success:false,error:"Invalid offer",code:"VALIDATION_ERROR"};const actor=await resolveProjectsActor();if(!actor.ok)return{success:false,error:"Not allowed",code:"FORBIDDEN"};const{error}=await actor.db.rpc("publish_project_commercial_offer",{p_order_id:projectId,p_offer_notes:offerNotes??null});if(error)return{success:false,error:error.message.includes("OFFER_NOT_READY")?"Save a complete, current offer before publishing":"You are not allowed to publish this offer",code:error.message.includes("FORBIDDEN")?"FORBIDDEN":"CONFLICT"};revalidatePath(`/projects/${projectId}`);revalidatePath("/projects");return getProjectCommercialRollup(projectId)}
export async function decideProjectCommercialOffer(raw:unknown):Promise<ActionResult<CommercialRollupState>>{const parsed=decisionSchema.safeParse(raw);if(!parsed.success)return{success:false,error:parsed.error.issues[0]?.message??"Invalid decision",code:"VALIDATION_ERROR"};const actor=await resolveProjectsActor();if(!actor.ok)return{success:false,error:"Not allowed",code:"FORBIDDEN"};const{error}=await actor.db.rpc("decide_project_commercial_offer",{p_order_id:parsed.data.projectId,p_decision:parsed.data.decision,p_notes:parsed.data.notes??null});if(error)return{success:false,error:error.message.includes("OFFER_NOT_OPEN")?"This offer can no longer be decided":"You are not allowed to decide this offer",code:"CONFLICT"};revalidatePath(`/projects/${parsed.data.projectId}`);revalidatePath("/projects");return getProjectCommercialRollup(parsed.data.projectId)}
