"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createAdminClient as createTypedAdminClient } from "@/lib/supabase/admin";
import type { DbClient } from "../../orders/services/dealModel";
import type { ActionResult } from "../../orders/types";
import { requireVisibleProject } from "./_projectAccess";
import { nextOfficialImagePosition } from "../officialImagePolicy";
const uuid=z.string().uuid();const admin=()=>createTypedAdminClient() as unknown as DbClient;
type Access=Extract<Awaited<ReturnType<typeof requireVisibleProject>>,{ok:true}>;
type ProjectRow={id:string;spine_id:string|null;buyer_organisation_id:string|null;seller_organisation_id:string|null};
async function context(projectId:string,write:boolean){const access=await requireVisibleProject(projectId,write);if(!access.ok)return null;const{data}=await access.actor.db.from("orders").select("id,spine_id,buyer_organisation_id,seller_organisation_id").eq("id",projectId).is("deleted_at",null).maybeSingle();return data?.spine_id?{access,project:data as ProjectRow}:null}
async function mayManage(access:Access,project:ProjectRow){if(access.actor.isPlatformAdmin)return true;if(!access.actor.orgId||project.seller_organisation_id!==access.actor.orgId)return false;const{data}=await access.actor.db.from("organisations").select("is_active,is_trader").eq("id",access.actor.orgId).maybeSingle();return data?.is_active===true&&data.is_trader===true}
async function mayRemove(access:Access,project:ProjectRow){return access.actor.isPlatformAdmin||Boolean(access.actor.orgId&&(project.buyer_organisation_id===access.actor.orgId||await mayManage(access,project)))}
async function refresh(spineId:string){const{data}=await admin().from("orders").select("id").eq("spine_id",spineId).is("deleted_at",null);for(const row of data??[])revalidatePath(`/projects/${row.id}`);revalidatePath("/projects")}
async function mutate(ctx:{access:Access;project:ProjectRow},fileId:string,action:"add"|"remove"|"default"):Promise<ActionResult<number|null>>{const{data,error}=await admin().rpc("mutate_spine_project_image",{p_spine_id:ctx.project.spine_id,p_file_id:fileId,p_action:action,p_created_by:ctx.access.actor.portalUserId});if(error)return{success:false,error:error.message.includes("IMAGE_LIMIT")?"A project can have up to three official images":"Could not update project image",code:"UPDATE_FAILED"};await refresh(ctx.project.spine_id!);return{success:true,data:data==null?null:Number(data)}}
export async function checkProjectOfficialImageSlot(projectId:string):Promise<ActionResult<{position:number}>>{if(!uuid.safeParse(projectId).success)return{success:false,error:"Image unavailable",code:"NOT_FOUND"};const ctx=await context(projectId,true);if(!ctx||!await mayManage(ctx.access,ctx.project))return{success:false,error:"Not allowed",code:"FORBIDDEN"};const{data,error}=await admin().from("spine_project_images").select("position").eq("spine_id",ctx.project.spine_id);if(error)return{success:false,error:"Could not check project image availability",code:"UPDATE_FAILED"};const position=nextOfficialImagePosition((data??[]).map((row:{position:number})=>row.position));return position?{success:true,data:{position}}:{success:false,error:"A project can have up to three official images",code:"LIMIT_REACHED"}}
export async function completeProjectOfficialImage(projectId:string,fileId:string){return addProjectOfficialImage(projectId,fileId)}
export async function addProjectOfficialImage(projectId:string,fileId:string):Promise<ActionResult<{position:number}>>{if(!uuid.safeParse(projectId).success||!uuid.safeParse(fileId).success)return{success:false,error:"Image unavailable",code:"NOT_FOUND"};const ctx=await context(projectId,true);if(!ctx||!await mayManage(ctx.access,ctx.project))return{success:false,error:"Not allowed",code:"FORBIDDEN"};const{data:file,error:fileError}=await admin().from("order_files").select("id").eq("id",fileId).eq("order_id",projectId).eq("category","project").eq("file_variant","original").eq("lifecycle_status","ready").like("mime_type","image/%").maybeSingle();if(fileError||!file)return{success:false,error:"Image unavailable",code:"NOT_FOUND"};const result=await mutate(ctx,fileId,"add");return result.success&&result.data?{success:true,data:{position:result.data}}:result.success?{success:false,error:"Could not add project image",code:"UPDATE_FAILED"}:result}
export async function removeProjectOfficialImage(projectId:string,fileId:string):Promise<ActionResult<null>>{if(!uuid.safeParse(projectId).success||!uuid.safeParse(fileId).success)return{success:false,error:"Image unavailable",code:"NOT_FOUND"};const ctx=await context(projectId,false);if(!ctx||!await mayRemove(ctx.access,ctx.project))return{success:false,error:"Not allowed",code:"FORBIDDEN"};const result=await mutate(ctx,fileId,"remove");return result.success?{success:true,data:null}:result}
export async function setProjectOfficialImagePrimary(projectId:string,fileId:string):Promise<ActionResult<null>>{if(!uuid.safeParse(projectId).success||!uuid.safeParse(fileId).success)return{success:false,error:"Image unavailable",code:"NOT_FOUND"};const ctx=await context(projectId,true);if(!ctx||!await mayManage(ctx.access,ctx.project))return{success:false,error:"Not allowed",code:"FORBIDDEN"};const result=await mutate(ctx,fileId,"default");return result.success?{success:true,data:null}:result}
