#!/usr/bin/env python3
"""Generate + run a realistic catalog reseed for the 4 staging categories.

Wipes existing products/variants for the 4 categories (safe: agent_order_items.variant_id
is ON DELETE SET NULL, so order snapshots survive) and inserts consistent, realistic
fake data with SKUs, EUR prices, stock, packaging and field values. GBP is generated
afterwards by the portal "Update prices" conversion.
"""
import json, os, uuid, urllib.request

REF = open(os.path.expanduser("~/.supabase-ijl/staging-ref")).read().strip()
PAT = open(os.path.expanduser("~/.supabase-ijl/pat")).read().strip()

def q(s):  # SQL string literal
    return "'" + s.replace("'", "''") + "'"

def U():   # fresh uuid
    return str(uuid.uuid4())

# ── Categories ────────────────────────────────────────────────────────────
CAT = {
    "swp":     "a0000001-0000-0000-0000-000000000001",  # m2
    "stairs":  "d1fd92a4-1781-4635-b54b-db458b8433f5",  # piece
    "firewood":"9a89b80d-6ffe-440f-b609-7a6f6ff6b92a",  # m3
    "terrace": "6b1f1449-0ae2-4b4b-ba97-47e7e46557ec",  # m2
}

# ── Global field ids ──────────────────────────────────────────────────────
F = {
    "species":   "f0000001-0001-0000-0000-000000000001",
    "panel":     "f0000001-0002-0000-0000-000000000001",
    "processing":"f0000001-0003-0000-0000-000000000001",
    "humidity":  "f0000001-0004-0000-0000-000000000001",
    "quality":   "f0000001-0005-0000-0000-000000000001",
    "fsc":       "f0000001-0006-0000-0000-000000000001",
    "thickness": "f0000001-0007-0000-0000-000000000001",
    "width":     "f0000001-0008-0000-0000-000000000001",
    "length":    "f0000001-0009-0000-0000-000000000001",
}

# option id maps  value -> option_id
SPECIES = {"Oak":"6286bb0f-4471-468a-a1de-3364b69d5ba7","Ash":"e51155c7-f0e3-4055-bd35-c6cf4e51ebd2",
           "Birch":"6865e713-ac6c-42b5-ac6d-a1643d977dc0","Pine":"54c8e615-f750-4870-96ea-0587ba35f2dd"}
PANEL   = {"FJ":"e3689e35-1f51-46ae-a817-ce1797b76fcb","Full stave":"58837670-ce0c-4d5a-ad72-c6b443283d7f"}
PROC    = {"Planed":"fe9bb849-02dd-4998-b81b-da717b742c17","Sanded":"6f193264-710e-490b-b78b-52e482e17b0d",
           "Oiled":"d48eb342-0180-469f-b673-3a83dd6db430","Varnished":"59ec355c-22e0-4324-9f24-a6d64e1bd190"}
HUM     = {"Air dried":"13a767e5-a43d-46b3-b94a-583844a1a9a2","KD 7-9%":"66bd0514-90e0-46d6-9204-4b991f0cc08f",
           "KD 9-11%":"f2882b64-62d3-49f3-bfab-a45cf763273c"}
QUAL    = {"AA":"8f314ee1-e5fb-424a-9f4c-95cea88703be","AV":"44b9bbd3-c357-41d7-bb06-826be36e579f",
           "AB":"5088e588-8912-4a9a-b37e-253c885ba472","BC":"a5a37f6c-53e7-4b49-9417-2f038206869b",
           "Prime":"bc1d79e9-075c-439e-90f3-ea2be1875d25"}
FSC     = {"FSC 100%":"b31d993c-e7ae-4f86-930f-4b3cc285d698","Yes":"9e361bbe-9f2e-46df-9553-db32a85406c0",
           "No":"131a7b09-4a18-422d-8217-186b67ad5957"}

# ── New species options (global) ──────────────────────────────────────────
NEW_SPECIES = {  # value: (label, sort, option_id)
    "Larch": ("Siberian Larch", 5, U()),
    "Beech": ("European Beech", 6, U()),
    "Alder": ("Black Alder",    7, U()),
}
for v,(lab,so,oid) in NEW_SPECIES.items():
    SPECIES[v] = oid

# ── New field: surface_profile (for decking) ──────────────────────────────
PROFILE_FIELD = "f0000002-0001-0000-0000-000000000001"
PROFILE = {"Smooth":U(), "Grooved":U(), "Reeded":U()}

# packaging type ids
PKG = {"pallet":"f57c17cf-fc28-4e30-a8aa-19fa5d7e5e53","half":"2f14093a-0b70-4a69-8b51-52a966e2f2dc",
       "large":"c05d5f6a-c695-4d0b-b868-ddf29d917188","bundle":"3336df5a-f641-44e5-bab7-fd5ecf835323",
       "single":"6bc1e9cc-e447-4c34-84b3-5150939f6983"}

SP_CODE = {"Oak":"OAK","Ash":"ASH","Birch":"BIR","Pine":"PIN","Larch":"LAR","Beech":"BEE","Alder":"ALD"}

sql = []
def add(s): sql.append(s)

# ── 1. cleanup ────────────────────────────────────────────────────────────
cats = ",".join(q(c) for c in CAT.values())
add("BEGIN;")
# remove stale test carts so none point at deleted variants
add("DELETE FROM agent_order_items WHERE order_id IN (SELECT id FROM agent_orders WHERE status='cart');")
add("DELETE FROM agent_orders WHERE status='cart';")
# wipe products/variants for the 4 categories (variant children cascade; order snapshots keep, fk->null)
add(f"DELETE FROM catalog_variants WHERE product_id IN (SELECT id FROM catalog_products WHERE category_id IN ({cats}));")
add(f"DELETE FROM catalog_products WHERE category_id IN ({cats});")
add("DELETE FROM catalog_currency_prices;")  # regenerated by conversion

# ── 2. new species options ────────────────────────────────────────────────
for v,(lab,so,oid) in NEW_SPECIES.items():
    add(f"INSERT INTO catalog_field_options (id,field_id,value,label,sort_order) "
        f"VALUES ({q(oid)},{q(F['species'])},{q(v)},{q(lab)},{so}) "
        f"ON CONFLICT (field_id,value) DO NOTHING;")

# ── 3. surface_profile field + options ────────────────────────────────────
add(f"INSERT INTO catalog_fields (id,field_key,field_label,field_type) "
    f"VALUES ({q(PROFILE_FIELD)},'surface_profile','Surface Profile','select') "
    f"ON CONFLICT (field_key) DO NOTHING;")
for i,(v,oid) in enumerate(PROFILE.items(),1):
    add(f"INSERT INTO catalog_field_options (id,field_id,value,label,sort_order) "
        f"VALUES ({q(oid)},{q(PROFILE_FIELD)},{q(v)},{q(v)},{i}) ON CONFLICT (field_id,value) DO NOTHING;")

# ── 4. commissions on the 3 new categories ────────────────────────────────
add(f"UPDATE catalog_categories SET commission_standard_pct=18,commission_max_discount_pct=12,commission_discounted_pct=9 WHERE id={q(CAT['stairs'])};")
add(f"UPDATE catalog_categories SET commission_standard_pct=12,commission_max_discount_pct=8, commission_discounted_pct=6 WHERE id={q(CAT['firewood'])};")
add(f"UPDATE catalog_categories SET commission_standard_pct=20,commission_max_discount_pct=15,commission_discounted_pct=10 WHERE id={q(CAT['terrace'])};")

# ── 5. field assignments for new categories ───────────────────────────────
def assign(cat, field, applies, filt, so):
    add(f"INSERT INTO catalog_category_field_assignments (category_id,field_id,applies_to,show_in_filter,show_in_detail,show_in_price_list,is_required,sort_order) "
        f"VALUES ({q(cat)},{q(field)},{q(applies)},{str(filt).lower()},true,{'true' if applies=='variant' else 'false'},false,{so}) "
        f"ON CONFLICT (category_id,field_id) DO NOTHING;")

# stairs: species, processing(finish), quality(variant), dims
for fld,ap,fl,so in [("species","product",True,1),("processing","product",False,2),
                     ("quality","variant",True,3),("thickness","variant",True,4),
                     ("width","variant",False,5),("length","variant",False,6)]:
    assign(CAT["stairs"], F[fld], ap, fl, so)
# firewood: species, humidity(moisture), dims
for fld,ap,fl,so in [("species","product",True,1),("humidity","product",True,2),
                     ("thickness","variant",False,3),("width","variant",False,4),("length","variant",False,5)]:
    assign(CAT["firewood"], F[fld], ap, fl, so)
# terrace: species, surface_profile, quality(variant), dims
assign(CAT["terrace"], F["species"], "product", True, 1)
add(f"INSERT INTO catalog_category_field_assignments (category_id,field_id,applies_to,show_in_filter,show_in_detail,show_in_price_list,is_required,sort_order) "
    f"VALUES ({q(CAT['terrace'])},{q(PROFILE_FIELD)},'product',true,true,false,false,2) ON CONFLICT (category_id,field_id) DO NOTHING;")
for fld,ap,fl,so in [("quality","variant",True,3),("thickness","variant",True,4),
                     ("width","variant",False,5),("length","variant",False,6)]:
    assign(CAT["terrace"], F[fld], ap, fl, so)

# ── helpers to emit a product + variants ──────────────────────────────────
def product(cat, slug, name, desc, sort, base_eur_cents, pvals):
    pid = U()
    add(f"INSERT INTO catalog_products (id,category_id,slug,name,description,sort_order,base_price_eur_cents) "
        f"VALUES ({q(pid)},{q(cat)},{q(slug)},{q(name)},{q(desc)},{sort},{base_eur_cents});")
    for fid,oid in pvals:
        add(f"INSERT INTO catalog_product_field_values (product_id,field_id,option_id) VALUES ({q(pid)},{q(fid)},{q(oid)});")
    return pid

def variant(pid, sku, thk, w, l, price_cents, stock_qty, stock_unit, pkg, vvals, sort):
    vid = U()
    add(f"INSERT INTO catalog_variants (id,product_id,sku,thickness_mm,width_mm,length_mm,price_eur_cents,stock_quantity,stock_unit,sort_order) "
        f"VALUES ({q(vid)},{q(pid)},{q(sku)},{thk},{w},{l},{price_cents},{stock_qty},{q(stock_unit)},{sort});")
    add(f"INSERT INTO catalog_variant_packaging_assignments (variant_id,packaging_type_id,is_default) VALUES ({q(vid)},{q(pkg)},true);")
    for fid,oid in vvals:
        add(f"INSERT INTO catalog_variant_field_values (variant_id,field_id,option_id) VALUES ({q(vid)},{q(fid)},{q(oid)});")
    return vid

def stock_for(seed):  # deterministic pseudo stock
    return 30 + (abs(hash(seed)) % 46) * 10  # 30..480

# ══════════════════════════════════════════════════════════════════════════
# SOLID WOOD PANELS  (per m²)
# ══════════════════════════════════════════════════════════════════════════
swp_products = [
    ("oak-full-stave","Oak Full Stave Panel","Oak","Full stave",62,"AA","FSC 100%",
     "Premium European oak full-stave panels. Long, unjointed staves edge-glued for an uninterrupted, furniture-grade grain. Kiln dried and sanded, ready for worktops, shelving and joinery."),
    ("oak-finger-joint","Oak Finger Joint Panel","Oak","FJ",44,"AV","FSC 100%",
     "European oak finger-jointed panels. Shorter staves jointed end-to-end for excellent stability and value, with the warmth and durability of solid oak."),
    ("ash-full-stave","Ash Full Stave Panel","Ash","Full stave",54,"AA","Yes",
     "European ash full-stave panels with a bright tone and bold, flowing grain. A strong, resilient hardwood ideal for contemporary furniture and stair parts."),
    ("ash-finger-joint","Ash Finger Joint Panel","Ash","FJ",39,"AV","Yes",
     "European ash finger-jointed panels. Pale, hard-wearing and dimensionally stable — a cost-effective choice for interior joinery."),
    ("birch-full-stave","Birch Full Stave Panel","Birch","Full stave",47,"AB","FSC 100%",
     "Nordic birch full-stave panels. Fine, even grain and a smooth, light surface that takes paint and lacquer beautifully."),
    ("birch-finger-joint","Birch Finger Joint Panel","Birch","FJ",34,"AB","FSC 100%",
     "Nordic birch finger-jointed panels. Clean and uniform, well suited to cabinetry, drawers and painted furniture."),
    ("pine-finger-joint","Pine Finger Joint Panel","Pine","FJ",28,"BC","No",
     "Scandinavian pine finger-jointed panels. A warm, knotty softwood panel — economical for shelving, cladding and rustic interiors."),
]
swp_dims = [(18,600,2000),(18,620,3000),(20,620,2000),(26,800,3000),(40,620,2000),(40,800,4000)]
for i,(slug,name,sp,pt,base,grade,fsc,desc) in enumerate(swp_products):
    pvals=[(F["species"],SPECIES[sp]),(F["panel"],PANEL[pt]),(F["processing"],PROC["Sanded"]),(F["humidity"],HUM["KD 7-9%"])]
    pid=product(CAT["swp"],slug,name,desc,i,base*100,pvals)
    for j,(thk,w,l) in enumerate(swp_dims):
        eur=round((base + (thk-18)*0.9)*100)
        sku=f"SWP-{SP_CODE[sp]}{'FS' if pt=='Full stave' else 'FJ'}-{thk}x{w}x{l}"
        vv=[(F["quality"],QUAL[grade]),(F["fsc"],FSC[fsc])]
        su="package" if j%3==0 else "piece"
        variant(pid,sku,thk,w,l,eur,stock_for(sku),su,PKG["pallet"],vv,j)

# ══════════════════════════════════════════════════════════════════════════
# STAIR THREADS  (per piece)
# ══════════════════════════════════════════════════════════════════════════
stair_products = [
    ("oak-stair-tread","Oak Stair Tread","Oak",38,"Prime","Oiled",
     "Solid European oak stair treads, edge-glued from prime staves and pre-oiled. Ready to install for a warm, hard-wearing staircase."),
    ("ash-stair-tread","Ash Stair Tread","Ash",30,"AA","Sanded",
     "Solid ash stair treads with a bright, even grain. Sanded and ready for your choice of finish."),
    ("beech-stair-tread","Beech Stair Tread","Beech",26,"AA","Sanded",
     "European beech stair treads — dense, smooth and pale. An economical, durable choice for interior stairs."),
]
stair_dims=[(40,300,900),(40,300,1000),(40,330,1100),(40,330,1200),(40,330,1300)]
for i,(slug,name,sp,base,grade,fin,desc) in enumerate(stair_products):
    pvals=[(F["species"],SPECIES[sp]),(F["processing"],PROC[fin])]
    pid=product(CAT["stairs"],slug,name,desc,i,base*100,pvals)
    for j,(thk,w,l) in enumerate(stair_dims):
        eur=round((base + (l-900)/100*3.5 + (w-300)*0.03)*100)
        sku=f"STR-{SP_CODE[sp]}-{thk}x{w}x{l}"
        vv=[(F["quality"],QUAL[grade])]
        variant(pid,sku,thk,w,l,eur,stock_for(sku),"piece",PKG["bundle"],vv,j)

# ══════════════════════════════════════════════════════════════════════════
# FIRE WOOD  (per m³)  — each variant is a crate; volume = w*l*t (m³)
# ══════════════════════════════════════════════════════════════════════════
fw_products = [
    ("oak-firewood","Oak Firewood (Kiln-Dried)","Oak",110,"KD 7-9%",
     "Premium kiln-dried oak firewood. High density and a long, hot burn with low moisture — ideal for wood burners and open fires."),
    ("birch-firewood","Birch Firewood (Kiln-Dried)","Birch",95,"KD 7-9%",
     "Kiln-dried birch firewood. Lights easily and burns bright and clean with a pleasant aroma."),
    ("alder-firewood","Alder Firewood (Kiln-Dried)","Alder",78,"KD 9-11%",
     "Kiln-dried alder firewood. A clean, even burn — excellent value for regular use."),
    ("mixed-hardwood-firewood","Mixed Hardwood Firewood (Air-Dried)","Birch",62,"Air dried",
     "Air-dried mixed hardwood firewood. A budget-friendly blend for seasoning further or for outdoor fire pits."),
]
# (label thk w l) crate dimensions giving nice m3
fw_crates=[("1.0 m³ crate",1000,1000,1000),("1.5 m³ crate",1000,1500,1000),("2.0 m³ crate",1000,2000,1000)]
for i,(slug,name,sp,base,moist,desc) in enumerate(fw_products):
    pvals=[(F["species"],SPECIES[sp]),(F["humidity"],HUM[moist])]
    pid=product(CAT["firewood"],slug,name,desc,i,base*100,pvals)
    for j,(lab,thk,w,l) in enumerate(fw_crates):
        vol=(thk/1000)*(w/1000)*(l/1000)
        eur=round((base - (vol-1.0)*4)*100)  # mild bulk discount
        sku=f"FW-{SP_CODE[sp]}-{vol:.1f}M3".replace('.0M3','M3')
        variant(pid,sku,thk,w,l,eur,stock_for(sku),"piece",PKG["single"],[],j)

# ══════════════════════════════════════════════════════════════════════════
# TERRACE FLOOR BOARDS  (per m²)
# ══════════════════════════════════════════════════════════════════════════
terrace_products = [
    ("oak-decking","Oak Decking","Oak",72,"Grooved","AA",
     "Solid European oak decking with a grooved anti-slip face. A premium, naturally durable terrace board that silvers gracefully over time."),
    ("siberian-larch-decking","Siberian Larch Decking","Larch",32,"Grooved","AB",
     "Dense, slow-grown Siberian larch decking. Naturally resinous and weather-resistant with a warm honey tone and a grooved surface."),
    ("thermo-ash-decking","Thermo-Ash Decking","Ash",58,"Smooth","AA",
     "Thermally modified ash decking. Heat treatment gives outstanding dimensional stability and durability with a rich, deep-brown colour."),
    ("pine-decking","Scandinavian Pine Decking","Pine",24,"Reeded","BC",
     "Pressure-treatable Scandinavian pine decking with a reeded face. An economical, versatile board for garden terraces and walkways."),
]
terrace_dims=[(26,120,3000),(28,120,4000),(28,140,4000),(45,140,5000),(45,140,6000)]
for i,(slug,name,sp,base,prof,grade,desc) in enumerate(terrace_products):
    pvals=[(F["species"],SPECIES[sp]),(PROFILE_FIELD,PROFILE[prof])]
    pid=product(CAT["terrace"],slug,name,desc,i,base*100,pvals)
    for j,(thk,w,l) in enumerate(terrace_dims):
        eur=round((base + (thk-26)*0.5 + (l-3000)/1000*0.4)*100)
        sku=f"TFB-{SP_CODE[sp]}-{thk}x{w}x{l}"
        vv=[(F["quality"],QUAL[grade])]
        su="package" if j%2==0 else "piece"
        variant(pid,sku,thk,w,l,eur,stock_for(sku),su,PKG["pallet"],vv,j)

add("COMMIT;")

full_sql = "\n".join(sql)
open(os.path.dirname(os.path.abspath(__file__))+"/seed_catalog_staging.sql","w").write(full_sql)
print(f"Generated {len(sql)} statements, {len(full_sql)} chars")

# ── run via Management API ────────────────────────────────────────────────
req = urllib.request.Request(
    f"https://api.supabase.com/v1/projects/{REF}/database/query",
    data=json.dumps({"query": full_sql}).encode(),
    headers={"Authorization": f"Bearer {PAT}", "Content-Type": "application/json"},
    method="POST")
try:
    resp = urllib.request.urlopen(req)
    print("HTTP", resp.status, resp.read().decode()[:500])
except urllib.error.HTTPError as e:
    print("ERROR", e.code, e.read().decode()[:1000])
