"use client";

import { useRef, useState } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { ChevronDown, ChevronUp, ImageIcon, Loader2, Trash2, Upload } from "lucide-react";
import { Button } from "@timber/ui";
import { toast } from "sonner";
import type { ProjectFileMeta } from "../types";
import { uploadProjectBrowserFile } from "./projectUploadClient";
import { addProjectOfficialImage, removeProjectOfficialImage } from "../actions/projectOfficialImageActions";

export function ProjectOfficialImages({projectId,initialFiles}:{projectId:string;initialFiles:ProjectFileMeta[]}) {
  const router=useRouter(); const [files,setFiles]=useState(initialFiles); const [busy,setBusy]=useState(false); const [open,setOpen]=useState(()=>initialFiles.some((file)=>file.officialImagePosition)); const input=useRef<HTMLInputElement>(null);
  const images=files.filter((file)=>file.officialImagePosition).sort((a,b)=>(a.officialImagePosition??0)-(b.officialImagePosition??0));
  async function upload(selected:FileList|null){if(!selected?.length)return;const remaining=3-images.length;if(selected.length>remaining)return toast.error(`You can add ${remaining} more official image${remaining===1?"":"s"}`);setBusy(true);try{const added:ProjectFileMeta[]=[];for(const file of Array.from(selected)){if(!file.type.startsWith("image/"))throw new Error("Official project files must be images");const uploaded=await uploadProjectBrowserFile(projectId,file,`Official images/${file.name}`,()=>{});const marked=await addProjectOfficialImage(projectId,uploaded.id);if(!marked.success)throw new Error(marked.error);added.push({...uploaded,officialImagePosition:marked.data.position,previewUrl:URL.createObjectURL(file)});}setFiles((current)=>[...current,...added]);router.refresh();toast.success("Official image uploaded");}catch(error){toast.error(error instanceof Error?error.message:"Could not upload image");}finally{setBusy(false);if(input.current)input.current.value="";}}
  async function remove(file:ProjectFileMeta){const result=await removeProjectOfficialImage(projectId,file.id);if(!result.success)return toast.error(result.error);setFiles((current)=>current.map((entry)=>entry.id===file.id?{...entry,officialImagePosition:null}:entry));router.refresh();}
  return <section className="overflow-hidden rounded-lg border bg-card"><button type="button" className="flex w-full items-center justify-between gap-3 p-4 text-left" aria-expanded={open} aria-controls="project-images-content" onClick={()=>setOpen((current)=>!current)}><span><span className="block text-xl font-semibold">Images</span><span className="block text-sm text-muted-foreground">{images.length > 0 ? `${images.length} of 3 project images` : "No images uploaded"}</span></span>{open?<ChevronUp className="h-4 w-4 text-muted-foreground"/>:<ChevronDown className="h-4 w-4 text-muted-foreground"/>}</button>{open?<div id="project-images-content" className="space-y-3 border-t p-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-muted-foreground">Up to three project images. The first image appears in the projects list.</p><><input ref={input} className="hidden" type="file" accept="image/*" multiple onChange={(event)=>void upload(event.target.files)}/><Button type="button" size="sm" disabled={busy||images.length>=3} onClick={()=>input.current?.click()}>{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Upload className="h-4 w-4"/>} Upload images</Button></></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-3">{[0,1,2].map((slot)=>{const file=images[slot];return <div key={slot} className="relative flex min-h-32 items-center justify-center overflow-hidden rounded-lg border bg-background">{file?<>{file.previewUrl?<Image src={file.previewUrl} alt={`Project image ${slot+1}`} fill unoptimized className="object-cover"/>:<ImageIcon className="h-6 w-6 text-muted-foreground/40"/>}<div className="absolute inset-x-0 bottom-0 flex items-center justify-between gap-2 bg-background/90 p-2"><span className="truncate text-xs">{slot+1}. {file.fileName}</span><Button type="button" size="icon" variant="ghost" aria-label={`Remove ${file.fileName}`} onClick={()=>void remove(file)}><Trash2 className="h-4 w-4"/></Button></div></>:<ImageIcon className="h-6 w-6 text-muted-foreground/40"/>}</div>})}</div></div>:null}</section>;
}
