"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2, Plus } from "lucide-react";
import { Button, Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger, Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@timber/ui";
import { toast } from "sonner";
import type { ProjectPartyOption } from "../types";
import type { SpineOriginAllocation } from "../services/spineOriginSpecification";
import { createSameSpineProjectLeg } from "../actions/projectLegActions";

const UNSET = "unset";
export function ProjectCreateLegDialog({ sourceProjectId, defaultBuyerId, buyerOptions, sellerOptions, allocation, initialOpen = false }: { sourceProjectId: string; defaultBuyerId: string | null; buyerOptions: ProjectPartyOption[]; sellerOptions: ProjectPartyOption[]; allocation: SpineOriginAllocation[]; initialOpen?: boolean }) {
  const router = useRouter(); const [open,setOpen]=useState(initialOpen); const [busy,setBusy]=useState(false); const [buyerId,setBuyerId]=useState(defaultBuyerId??UNSET); const [sellerId,setSellerId]=useState(UNSET); const [quantities,setQuantities]=useState<Record<string,number>>({});
  async function submit(){const workPackages=allocation.map((line)=>({originLineItemId:line.originLineItemId,quantity:quantities[line.originLineItemId]??0})).filter((line)=>line.quantity>0);setBusy(true);try{const result=await createSameSpineProjectLeg({sourceProjectId,buyerOrganisationId:buyerId===UNSET?null:buyerId,sellerOrganisationId:sellerId===UNSET?null:sellerId,workPackages});if(!result.success)return toast.error(result.error);toast.success("Project leg created");setOpen(false);router.push(`/projects/${result.data.projectId}`);router.refresh();}catch{toast.error("Could not create the project leg");}finally{setBusy(false)}}
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button type="button" variant="outline" size="sm"><Plus className="h-4 w-4" /> Create leg</Button></DialogTrigger><DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Create same-spine leg</DialogTitle><DialogDescription>Select either or both bilateral parties and the canonical origin work package. Prices start blank.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><PartyField label="Buyer" value={buyerId} options={buyerOptions} onChange={setBuyerId}/><PartyField label="Seller" value={sellerId} options={sellerOptions} onChange={setSellerId}/></div><fieldset className="space-y-3"><legend className="font-medium">Work package</legend>{allocation.length === 0 ? <p className="rounded-md border border-dashed p-4 text-sm text-muted-foreground">Add at least one line to the spine specification before creating a leg.</p> : allocation.map((line)=><label key={line.originLineItemId} className="grid grid-cols-[1fr_9rem] items-center gap-3 rounded-md border p-3"><span><span className="block font-medium">{line.lineNo}. {line.productName}</span><span className="text-xs text-muted-foreground">Required {line.requiredQuantity} · Awarded {line.awardedQuantity} · Remaining {line.remainingQuantity} {line.unit}</span></span><input aria-label={`Quantity for ${line.productName}`} className="h-9 rounded-md border bg-background px-3" type="number" min="0" max={line.remainingQuantity} step="any" value={quantities[line.originLineItemId]??""} onChange={(e)=>setQuantities((current)=>({...current,[line.originLineItemId]:Number(e.target.value)}))}/></label>)}</fieldset><DialogFooter><Button type="button" variant="ghost" onClick={()=>setOpen(false)} disabled={busy}>Cancel</Button><Button type="button" onClick={()=>void submit()} disabled={busy || allocation.length === 0}>{busy?<Loader2 className="h-4 w-4 animate-spin"/>:null} Create leg</Button></DialogFooter></DialogContent></Dialog>;
}
function PartyField({label,value,options,onChange}:{label:string;value:string;options:ProjectPartyOption[];onChange:(value:string)=>void}){return <label className="space-y-2"><span className="text-sm font-medium">{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value={UNSET}>Not assigned</SelectItem>{options.map((option)=><SelectItem key={option.id} value={option.id}>{option.code?`${option.code} — ${option.name}`:option.name}</SelectItem>)}</SelectContent></Select></label>}
