/**
 * Database types for Supabase
 * This file will be auto-generated by `npx supabase gen types typescript`
 * after the database schema is created
 */

export type Database = {
  public: {
    Tables: {
      products: {
        Row: {
          id: string
          sku: string
          species: string
          width: number
          length: number
          thickness: number
          quality_grade: string
          type: 'FJ' | 'FS'
          moisture_content: number
          finish: string | null
          fsc_certified: boolean
          unit_price_m3: number
          unit_price_piece: number
          unit_price_m2: number
          stock_quantity: number
          stock_status: 'in_stock' | 'low_stock' | 'out_of_stock'
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['products']['Row'], 'id' | 'created_at' | 'updated_at'> & {
          id?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['products']['Insert']>
      }
      quote_requests: {
        Row: {
          id: string
          reference_number: string
          type: 'stock' | 'custom'
          status: 'pending' | 'acknowledged' | 'responded' | 'followed_up' | 'converted' | 'closed'
          contact_name: string
          contact_email: string
          contact_phone: string | null
          company_name: string | null
          delivery_location: string | null
          products: unknown
          custom_specs: unknown
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['quote_requests']['Row'], 'id' | 'reference_number' | 'created_at' | 'updated_at'> & {
          id?: string
          reference_number?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['quote_requests']['Insert']>
      }
      admin_users: {
        Row: {
          id: string
          user_id: string
          email: string
          name: string
          role: string
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['admin_users']['Row'], 'id' | 'created_at' | 'updated_at'> & {
          id?: string
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['admin_users']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: {
      is_admin: {
        Args: Record<string, never>
        Returns: boolean
      }
      generate_quote_reference: {
        Args: Record<string, never>
        Returns: string
      }
    }
    Enums: {
      quote_type: 'stock' | 'custom'
      quote_status: 'pending' | 'acknowledged' | 'responded' | 'followed_up' | 'converted' | 'closed'
      stock_status: 'in_stock' | 'low_stock' | 'out_of_stock'
      product_type: 'FJ' | 'FS'
    }
  }
}

// Convenience type exports
export type Product = Database['public']['Tables']['products']['Row']
export type ProductInsert = Database['public']['Tables']['products']['Insert']
export type ProductUpdate = Database['public']['Tables']['products']['Update']

export type QuoteRequest = Database['public']['Tables']['quote_requests']['Row']
export type QuoteRequestInsert = Database['public']['Tables']['quote_requests']['Insert']
export type QuoteRequestUpdate = Database['public']['Tables']['quote_requests']['Update']

export type AdminUser = Database['public']['Tables']['admin_users']['Row']
export type AdminUserInsert = Database['public']['Tables']['admin_users']['Insert']
export type AdminUserUpdate = Database['public']['Tables']['admin_users']['Update']

export type QuoteType = Database['public']['Enums']['quote_type']
export type QuoteStatus = Database['public']['Enums']['quote_status']
export type StockStatus = Database['public']['Enums']['stock_status']
export type ProductType = Database['public']['Enums']['product_type']
